### ISSUE TITLE
Using Customer Timezone on Frontend Calendar

### ISSUE THREAD

**Issue by herofive2424** [RebelCode/edd-bookings#35]
Hello,

there is an option to use the customers timezone on the download frontend calendar when using EDD Bookings + FES.

In my opinion, it is **crucial** for this option to show the customer which timezone is used. (Like a short sentence beneath the calendar "You timezone: UTC+2")

Otherwise there can and will be confusion about the times.

How can this be achieved? (I'm able to insert code if it is needed)

If you can't tell me exactly what to insert, a hint where the relevant file is would be nice (as I find it difficult for myself to find it, what I already tried).

Thanks!

**Comment by mecha** [comment]
@herofive2424 You're right. Unfortunately, a _real_ fix is not currently possible by any _simple_ means. It would require a lot of changes in many different source code files, to the point that I am myself reluctant to even attempt it.

If you just want a quick working fix to show the customer's timezone, you can add the following code in [`assets/js/bookings-calendar.js#90`](https://github.com/RebelCode/edd-bookings/blob/develop/assets/js/bookings-calendar.js#L90) so that it is between `this.element.fullCalendar(fullCalendarArgs)` and the `};`.

```js
var timezoneOffset = ((new Date()).getTimezoneOffset() / (-60));
var timezoneSign = (timezoneOffset >= 0) ? "+" : "-";
var timezone = timezoneSign + Math.abs(timezoneOffset);
$('<p>Your timezone: UTC'+ timezone).insertAfter(this.element);
```

Remember that you will lose this change after a plugin update, and you will have to re-apply it.

**Sidenote:**  
Timezone handling is not properly implemented in the plugin, a known issue and one of the many reasons why we are currently re-building the plugin from the ground up for a v3.0. As such, we won't be fixing such issues in v2.2.4. We're aiming to release v3.0 in November, with FES integration coming in v3.1 a couple of months later.

**Comment by herofive2424** [comment]
@mecha Thank you for the fast response!

But I think there is a little misunderstanding here: Your fix is for the calendar shown to the **vendor** on the **fes vendor dashboard**. (Which was still helpfull though as I was also struggling with that!)

I was initially talking about the calendar shown to the **customer** on the **single download page**.
So that above or under this calendar would appear "Your timezone: UTC+2"(As the times in the calendar are already adjusted through the "Use the customers timezone" option).

The intention is to just make clear to the customer that the calendar is already adjusted (and the **correct** timezone was detected) to his timezone, so that he doesn't have to ask himself: Is that my local timezone or the platforms timezone, or maybe the vendors timezone? (as we are an international booking platform).

Would it be possible to have a small fix here aswell?

Again, thanks so much!

**Comment by mecha** [comment]
@herofive2424 Oh my bad, I completely misunderstood.

Try the following code in [`assets/js/eddbk/widget/service-session-picker.js#35`](https://github.com/RebelCode/edd-bookings/blob/develop/assets/js/eddbk/widget/service-session-picker.js#L35):

```js
var timezoneOffset = ((new Date()).getTimezoneOffset() / (-60));
var timezoneSign = (timezoneOffset >= 0) ? "+" : "-";
var timezone = timezoneSign + Math.abs(timezoneOffset);
$('<div><p>Your timezone: UTC' + timezone + '</p>').appendTo(this.msgs);
```

**Comment by herofive2424** [comment]
@mecha Works perfect, thank you!

**Comment by mecha** [comment]
You're welcome 😃
